### ISSUE TITLE
Task assignment delays

### ISSUE THREAD

**Issue by xyluz** [StayBusy/StayBusySlim#38]
When assigning a task to a user on the admin panel, the response on whether the process was successful or not takes too long and in some cases, the user doesn't get a response until after they refresh the page. This happens even though, for example, the task assignment process is already complete on the backend, the front-end doesn't get updated until after a while.

This behavior isn't present when removing a task assignment from a user, it's instantaneous.

**Comment by xyluz** [comment]
@orobogenius I could not re-create this.

**Comment by orobogenius** [comment]
@xyluz I just tried it, same thing. When you click on the check button on the task assignment page, it just keeps loading without any response for a while, which is unusually long, and then shows the success message. At times, it doesn't even show the success message until after page refresh.

I think the major concern now is, it takes too long to display the message, even on local but unassigning tasks is instant.

Also, I noticed another minor bug, when you assign and unassign tasks, the total tasks count on the page doesn't get updated.

**Comment by xyluz** [comment]
@orobogenius please test this, I could not really re-create it, but I noticed it was taking time to carry out the task assignment, I just stopped sending the email immediately and queued it instead. I think that should be the delay.

**Comment by orobogenius** [comment]
Ok, much better now.

**Comment by orobogenius** [comment]
Did you get a chance to check the total task count that doesn't get updated?

**Comment by xyluz** [comment]
That's true, I haven't. I'll get that done now.

**Comment by xyluz** [comment]
Done.
