### ISSUE TITLE
User Rating

### ISSUE THREAD

**Issue by orobogenius** [StayBusy/StayBusySlim#44]
Admin can drop review for users (in form of stars) this can help in assigning tasks to users. This review will be per-task submitted, And then an aggregate would be taken to form a more complete rating.

- [x] Create task review
- [x] Update task review

**Comment by orobogenius** [comment]
@xyluz would this allow multiple admis go give ratings to a single user's task?

**Comment by xyluz** [comment]
No. Only a single admin can accept/reject a task per time. If the admin accepts the task, only he can drop a review.
