### ISSUE TITLE
User Public Profile

### ISSUE THREAD

**Issue by orobogenius** [StayBusy/StayBusySlim#45]
User will have public profile, a way for them to share their progress with those who don't have account on staybusy.

**Comment by orobogenius** [comment]
@xyluz it would seem this feature already exists on alpha, perhaps it just needs more data to provide a more comprehensive profile?

**Comment by xyluz** [comment]
Yes, you are right. We need a more comprehensive public profile e.g reviews, etc.

**Comment by xyluz** [comment]
@orobogenius that's this ticket
