### ISSUE TITLE
Can't restart task after rejection.

### ISSUE THREAD

**Issue by orobogenius** [StayBusy/StayBusySlim#55]
A user is unable to restart a task after it has been rejected. The page throws a **MethodNotAllowedHttpException** exception and errors out.

**Comment by xyluz** [comment]
@orobogenius I was able to restart a task. Please try it again, maybe the scattered UI caused the error.

**Comment by orobogenius** [comment]
Still unable to restart, I get the **MethodNotAllowedHttpException**.

**Comment by xyluz** [comment]
are you trying to do that from @{username}/tasks (rejected tab)?

**Comment by xyluz** [comment]
> > Did you pull? Also, where are you trying to restart from?
> 
> From the **New Tasks** tab. I just used the one from the **Rejected tasks** tab and it worked but the one on the **New Tasks** tab doesn't.

Okay, i see. thanks.

**Comment by xyluz** [comment]
FIxed
