### ISSUE TITLE
Pages Needed

### ISSUE THREAD

**Issue by xyluz** [StayBusy/StayBusySlim#58]
- [x] Unauthorized Page: when a user tries to visit a page he's not allowed to view, e.g normal user trying to get to the admin page.
- [x] We need our task review page to accommodate the new features i.e. user rating
- [x] Marketplace
- [x] Update the single task page, make it follow the new profile pattern

**Comment by orobogenius** [comment]
@xyluz what do I test?

**Comment by xyluz** [comment]
@orobogenius check that unauthorized page is there, i.e when a user tries to get to admin pages, also check that single task page has a new look.

**Comment by orobogenius** [comment]
Ok. Single task page has a new look but unauthorized page doesn't.

**Comment by xyluz** [comment]
What does unauthorized look like for you?

**Comment by orobogenius** [comment]
Laravel's error page.

**Comment by xyluz** [comment]
PLease check again. dev.

**Comment by orobogenius** [comment]
Ok, the page comes up now.
