### ISSUE TITLE
Remake the migrations, add foreign keys where possible too. And the seeders, they're all commented out, don't know why

### ISSUE THREAD

**Issue by xyluz** [StayBusy/StayBusySlim#63]

**Comment by wisdomanthoni** [comment]
@xyluz What's up with this issue ....

**Comment by xyluz** [comment]
@wisdomanthoni you can take it on. It's open. But, you'll have to create a new branch from dev... feature/remake-migrations

**Comment by wisdomanthoni** [comment]
Ok ... 👍

**Comment by wisdomanthoni** [comment]
@xyluz  test here  https://github.com/StayBusy/StayBusySlim/tree/feature/remake-migrations
