### ISSUE TITLE
Send email to users when their task has been reviewed.

### ISSUE THREAD

**Issue by xyluz** [StayBusy/StayBusySlim#64]

**Comment by orobogenius** [comment]
Done @xyluz, please test.

**Comment by xyluz** [comment]
@orobogenius which branch?

**Comment by orobogenius** [comment]
Dev @xyluz

**Comment by xyluz** [comment]
![capture](https://user-images.githubusercontent.com/13081285/50531393-bf887a80-0abd-11e9-83c1-c1abaa57500f.PNG)

This should say "hello test" (since test is the name of the user), instead it says hello superadmin (that's the name of the admin that updated his review)

**Comment by xyluz** [comment]
And, it should not be sent to superadmin, it should be sent to the user

**Comment by orobogenius** [comment]
This mixup only happens when you update a review, right? @xyluz

**Comment by orobogenius** [comment]
Fixed.

**Comment by orobogenius** [comment]
@xyluz did you try this again?

**Comment by xyluz** [comment]
Give me a minute.

**Comment by xyluz** [comment]
Done. Now works.
