### ISSUE TITLE
Forum Update

### ISSUE THREAD

**Issue by xyluz** [StayBusy/StayBusySlim#73]
The following should be done on forum

- [x] Allow user subscribe to a particular topic, hence they get an email when the topic is updated
- [x] Allow users subscribe to the entire forum so that they get an email whenever any new post created on the forum

**Comment by wisdomanthoni** [comment]
This one no go easy ohh ... 😆

**Comment by xyluz** [comment]
@wisdomanthoni lol, actually, @gabumoh is looking at it, maybe you guys can work on it together... let me add you to the beta team..

**Comment by wisdomanthoni** [comment]
@gabumoh the first one has been enabled ...

**Comment by xyluz** [comment]
@wisdomanthoni don't forget that emails should be queued...
