### ISSUE TITLE
Task Submission Error

### ISSUE THREAD

**Issue by orobogenius** [StayBusy/StayBusySlim#82]
I'm unable to submit a completed task from the user's dashboard, see attached image.

Route: `/@username/tasks`

![screenshot 2019-02-02 at 9 52 12 pm](https://user-images.githubusercontent.com/11756231/52169468-3fe37080-2739-11e9-8760-0803e8fbb455.png)

**Comment by wisdomanthoni** [comment]
@orobogenius pull and test this too

**Comment by orobogenius** [comment]
@wisdomanthoni This works now, sorry for the delay.
